using System;
using System.Collections.Generic;

namespace ApiStorage.Models
{
    /**
     * Autogenerated by entity framework using the following command
     * dotnet ef dbcontext scaffold "Data Source=LIMAPELP348;Initial Catalog=ApiStorage;User Id=sa;Password=0112Password!@" Microsoft.EntityFrameworkCore.SqlServer -o Models
     */
    public partial class Storage
    {
        public int StorageId { get; set; }
        public string? StorageName { get; set; }
        public string? StorageAddress { get; set; }
        public decimal? StorageCapacity { get; set; }
    }
}
