// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Practice02_01.DbContexts;

#nullable disable

namespace Test_Practice02_01.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Test_Practice02_01.Models.ShipDocument", b =>
                {
                    b.Property<int>("shipDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipDocumentId"), 1L, 1);

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<string>("customerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerRuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("driverId")
                        .HasColumnType("int");

                    b.Property<string>("driverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("shipDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("totalBoxes")
                        .HasColumnType("int");

                    b.Property<int>("totalWeight")
                        .HasColumnType("int");

                    b.HasKey("shipDocumentId");

                    b.ToTable("shipDocuments");
                });

            modelBuilder.Entity("Test_Practice02_01.Models.ShipDocumentDetail", b =>
                {
                    b.Property<int>("shipDocumentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipDocumentDetailId"), 1L, 1);

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("shipDocumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("subTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("shipDocumentDetailId");

                    b.HasIndex("shipDocumentId");

                    b.ToTable("shipDocumentDetails");
                });

            modelBuilder.Entity("Test_Practice02_01.Models.ShipDocumentDetail", b =>
                {
                    b.HasOne("Test_Practice02_01.Models.ShipDocument", "shipDocument")
                        .WithMany("shipDocumentDetails")
                        .HasForeignKey("shipDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shipDocument");
                });

            modelBuilder.Entity("Test_Practice02_01.Models.ShipDocument", b =>
                {
                    b.Navigation("shipDocumentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
